### ISSUE TITLE
[web] Initial MVP

### ISSUE THREAD

**Issue by jxson** [vanadium/reader#4]
* [x] Test/lint tooling and CI setup #2
* [x] Discovery: discover and connect to peers #3
* [ ] Discovery: update on peer removal (disconnect, user initiated, etc.) #5
* [x] UI component tools initial boilerplate/setup [CL#14522](https://v.io/c/14522/)
* [x] Add PDF files and store them locally [CL#14522](https://v.io/c/14522/)
* [x] Synchronize PDF files across peers #6
* [x] PDF controls for navigating pages, controlling zoom, etc. #7
* [x] Syncbase integration #8
* [ ] Device set management (add/remove/manage peers so they can simultaneously read the same PDF) #9
* [ ] Latency measurements around Vanadium and Syncbase activity #10 (maybe some [perf analysis](https://developers.google.com/web/tools/profile-performance/rendering-tools/js-execution))
* [ ] Debug view of peers and state (discovery, Syncbase activity, latency) #11
* [ ] Error component

/cc @jwnichls
